### ISSUE TITLE
migen only wrapper for fomu

### ISSUE THREAD

**Issue by aMOPel** [no2fpga/no2migen#1]
Hey there, is there any technical reason you didn't provide an example for the Migen only wrapper used with the Fomu?
Because in the readme it says:

> Some of the cores have limited FPGA architecture supports and will only work on some FPGA target

Skimming the code I didn't see a reason it wouldn't work on the Fomu, but maybe you've already hit a road bump and could share it, so I don't have to.

Thanks for your work.

**Comment by smunaut** [comment]
No, it should work just fine on Fomu, I just didn't write any example, but the one for the icebreaker should be easily modified to work, just using the fomu platform instead. Hit me up ( @tnt ) on the 1bitsquared discord if you're having trouble getting it to run.

**Comment by aMOPel** [comment]
Alright, thanks a lot.
